import { Inter, Merienda } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const merienda = Merienda({ subsets: ["latin"] });

export const metadata = {
  title: "PixShare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Merienda:wght@300..900&display=swap" rel="stylesheet"/>
      </head>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
